"""convert keywords and alias_names to JSON type

Revision ID: 8a375d54f25a
Revises: 5dd5ac16dcbe
Create Date: 2026-08-30 19:32:49.185802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a375d54f25a'
down_revision = '5dd5ac16dcbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('patient_instructions', sa.Text(), nullable=True),
    sa.Column('durations', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('alias_names', sa.JSON(), nullable=True),
    sa.Column('sample_type', sa.String(length=100), nullable=True),
    sa.Column('search_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labservices')
    # ### end Alembic commands ###
